
development:
  adapter: postgresql
  database: samantha
  host: 127.0.0.1
  port: 5432
  pool: 25
  timeout: 5000
  username: geeksters
  password: geeksters

test:
  adapter: postgresql
  database: samantha_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: 127.0.0.1
  port: 5432
  pool: 25
  timeout: 5000
  username: geeksters
  password: geeksters

production:
  adapter: postgresql
  database: samantha
  host: 127.0.0.1
  port: 5432
  pool: 25
  timeout: 5000
  username: geeksters
  password: geeksters
  #schema_search_path: <database_schema> (default - public)