production:
  adapter: postgresql
  database: redmine
  host: localhost
  username: adil
  password: 123456789
  encoding: utf8

development:
  adapter: postgresql
  database: redmine_dev
  host: localhost
  username: adil
  password: 123456789
  encoding: utf8

test:
    adapter: postgresql
    database: redmine_test
    host: localhost
    username: adil
    password: 123456789
    encoding: utf8
  #schema_search_path: <database_schema> (default - public)