# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: "6aec4903fe8259efe7d27f7d92c3a19e95ea4b0ffb55340993942d15aa22110bd1ec08e57b98f4f57df383815444303631f56028193874aa5e32caaa5e940bfa"

test:
  ssecret_key_base: "6aec4903fe8259efe7d27f7d92c3a19e95ea4b0ffb55340993942d15aa22110bd1ec08e57b98f4f57df383815444303631f56028193874aa5e32caaa5e940bfa"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>